### ISSUE TITLE
New Reviews pop-up doesn't take into account which game you are playing

### ISSUE THREAD

**Issue by Arcadius2006** [LittleBigRefresh/Refresh#600]
instead of checking for levels accesible from the game you're playing, refresh checks all your levels for if any new reviews were added

**Comment by jvyden** [comment]
I'm not sure what this is meant to mean. Where are you seeing this?

**Comment by Arcadius2006** [comment]
the "Me" section of the pod UI, it appears in form of a circular pop-up
for example: "There are 3 new reviews"

**Comment by jvyden** [comment]
In... LBP2? I'm not sure if that's really too big of a deal in that case, unless it's a full UI.

**Comment by Arcadius2006** [comment]
yeah, it's in LBP2, it pops up somewhat like this
![image](https://github.com/user-attachments/assets/d7d23ccb-7091-420a-9a04-929665aa9211)

**Comment by jvyden** [comment]
The server doesn't store a review count anywhere for the user. It's probably just summing up the reviews of every level it can see on the endpoint used for your earth (which is definitely filtered to the correct game version) and comparing it against the last time it saw.

I'd say whatever behavior you're seeing is probably entirely intentional.
