### ISSUE TITLE
Publishing/deleting levels is broken on LBP vita

### ISSUE THREAD

**Issue by speedyman09** [LittleBigRefresh/Refresh#73]
Please watch the attached video:

https://github.com/LittleBigRefresh/Refresh/assets/17880243/2fe1e8cb-db20-45a7-bae2-4a718394cf49

Publishing only worked once, and that explains how I published the "Flung." level

**Comment by turecross321** [comment]
The publishing problem is a LBP Vita bug and not a server bug. It usually happens if you have published the level to a different server before, and it can usually be fixed by copying the level to a different slot and publishing the copy. You can confirm this by taking a look at the console output. If you look closely you'll notice that the game never sends a publish request to the server.

The deletion bug was fixed recently, but hasn't made it to the latest release yet. You can download the latest artifcact [here](https://github.com/LittleBigRefresh/Refresh/actions).

**Comment by speedyman09** [comment]
I am now using the latest artifact, and when I login the server responds with a 403: 
![image](https://github.com/LittleBigRefresh/Refresh/assets/17880243/cd7e0a98-8de7-4348-8e8d-8cf5ca26ba51)

**Comment by speedyman09** [comment]
Forgot to include this warning in the previous screenshot 
![image](https://github.com/LittleBigRefresh/Refresh/assets/17880243/eebe1791-04a1-444f-91e8-3b92eb9b559b)

**Comment by turecross321** [comment]
This appears to be an issue with NPTicket 3.0.0. I'll make an issue for it

**Comment by speedyman09** [comment]
Jvy reverted the NPTicket update and it works now, thanks
